version: "2"

run:
  timeout: 5m

linters:
  default: all
  disable:
    - depguard

linters-settings:
  errcheck:
    check-type-assertions: true
  bidichk:
    # The following configurations check for all mentioned invisible Unicode runes.
    # All runes are enabled by default.
    left-to-right-embedding: false
    right-to-left-embedding: false
    pop-directional-formatting: false
    left-to-right-override: false
    right-to-left-override: false
    left-to-right-isolate: false
    right-to-left-isolate: false
    first-strong-isolate: false
    pop-directional-isolate: false
  copyloopvar:
    # Check all assigning the loop variable to another variable.
    # Default: false
    check-alias: true
  cyclop:
    max-complexity: 100
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          reflect: Please don't use reflect package
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
        deny:
          reflect: Please don't use reflect package
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 50
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand or math/rand/v2 instead of crypto/rand)
  lll:
    line-length: 150
  nestif:
    # Minimal complexity of if statements to report.
    min-complexity: 3

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  # Formatters settings.
  settings:
    # See the dedicated "formatters.settings" documentation section.
    option: value
  exclusions:
    # Log a warning if an exclusion path is unused.
    # Default: false
    warn-unused: true
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: lax
    generated: strict
    # Which file paths to exclude.
    # This option is ignored when using `--stdin` as the path is unknown.
    # Default: []
    paths:
      - "ext"

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 50
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 3
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: true
  new: false
#  exclude-rules:
#    - path: internal/handler/handler_test.go
#      linters:
#        - testpackage
#    - path: cmd/agent/main.go
#      linters:
#        - depguard
#  exclude-use-default: true

