// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/olelishna/urlshortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPersistentStorage creates a new instance of MockPersistentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersistentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersistentStorage {
	mock := &MockPersistentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersistentStorage is an autogenerated mock type for the PersistentStorage type
type MockPersistentStorage struct {
	mock.Mock
}

type MockPersistentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersistentStorage) EXPECT() *MockPersistentStorage_Expecter {
	return &MockPersistentStorage_Expecter{mock: &_m.Mock}
}

// GetShortByLongURL provides a mock function for the type MockPersistentStorage
func (_mock *MockPersistentStorage) GetShortByLongURL(ctx context.Context, longURL string) (string, error) {
	ret := _mock.Called(ctx, longURL)

	if len(ret) == 0 {
		panic("no return value specified for GetShortByLongURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, longURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, longURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, longURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersistentStorage_GetShortByLongURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShortByLongURL'
type MockPersistentStorage_GetShortByLongURL_Call struct {
	*mock.Call
}

// GetShortByLongURL is a helper method to define mock.On call
//   - ctx context.Context
//   - longURL string
func (_e *MockPersistentStorage_Expecter) GetShortByLongURL(ctx interface{}, longURL interface{}) *MockPersistentStorage_GetShortByLongURL_Call {
	return &MockPersistentStorage_GetShortByLongURL_Call{Call: _e.mock.On("GetShortByLongURL", ctx, longURL)}
}

func (_c *MockPersistentStorage_GetShortByLongURL_Call) Run(run func(ctx context.Context, longURL string)) *MockPersistentStorage_GetShortByLongURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersistentStorage_GetShortByLongURL_Call) Return(s string, err error) *MockPersistentStorage_GetShortByLongURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPersistentStorage_GetShortByLongURL_Call) RunAndReturn(run func(ctx context.Context, longURL string) (string, error)) *MockPersistentStorage_GetShortByLongURL_Call {
	_c.Call.Return(run)
	return _c
}

// LoadData provides a mock function for the type MockPersistentStorage
func (_mock *MockPersistentStorage) LoadData(ctx context.Context) (map[string]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadData")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersistentStorage_LoadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadData'
type MockPersistentStorage_LoadData_Call struct {
	*mock.Call
}

// LoadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPersistentStorage_Expecter) LoadData(ctx interface{}) *MockPersistentStorage_LoadData_Call {
	return &MockPersistentStorage_LoadData_Call{Call: _e.mock.On("LoadData", ctx)}
}

func (_c *MockPersistentStorage_LoadData_Call) Run(run func(ctx context.Context)) *MockPersistentStorage_LoadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPersistentStorage_LoadData_Call) Return(stringToString map[string]string, err error) *MockPersistentStorage_LoadData_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockPersistentStorage_LoadData_Call) RunAndReturn(run func(ctx context.Context) (map[string]string, error)) *MockPersistentStorage_LoadData_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEntries provides a mock function for the type MockPersistentStorage
func (_mock *MockPersistentStorage) SaveEntries(ctx context.Context, entries []model.Entry) error {
	ret := _mock.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for SaveEntries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Entry) error); ok {
		r0 = returnFunc(ctx, entries)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistentStorage_SaveEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEntries'
type MockPersistentStorage_SaveEntries_Call struct {
	*mock.Call
}

// SaveEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []model.Entry
func (_e *MockPersistentStorage_Expecter) SaveEntries(ctx interface{}, entries interface{}) *MockPersistentStorage_SaveEntries_Call {
	return &MockPersistentStorage_SaveEntries_Call{Call: _e.mock.On("SaveEntries", ctx, entries)}
}

func (_c *MockPersistentStorage_SaveEntries_Call) Run(run func(ctx context.Context, entries []model.Entry)) *MockPersistentStorage_SaveEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Entry
		if args[1] != nil {
			arg1 = args[1].([]model.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersistentStorage_SaveEntries_Call) Return(err error) *MockPersistentStorage_SaveEntries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistentStorage_SaveEntries_Call) RunAndReturn(run func(ctx context.Context, entries []model.Entry) error) *MockPersistentStorage_SaveEntries_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEntry provides a mock function for the type MockPersistentStorage
func (_mock *MockPersistentStorage) SaveEntry(ctx context.Context, entry model.Entry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for SaveEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Entry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistentStorage_SaveEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEntry'
type MockPersistentStorage_SaveEntry_Call struct {
	*mock.Call
}

// SaveEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry model.Entry
func (_e *MockPersistentStorage_Expecter) SaveEntry(ctx interface{}, entry interface{}) *MockPersistentStorage_SaveEntry_Call {
	return &MockPersistentStorage_SaveEntry_Call{Call: _e.mock.On("SaveEntry", ctx, entry)}
}

func (_c *MockPersistentStorage_SaveEntry_Call) Run(run func(ctx context.Context, entry model.Entry)) *MockPersistentStorage_SaveEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Entry
		if args[1] != nil {
			arg1 = args[1].(model.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersistentStorage_SaveEntry_Call) Return(err error) *MockPersistentStorage_SaveEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistentStorage_SaveEntry_Call) RunAndReturn(run func(ctx context.Context, entry model.Entry) error) *MockPersistentStorage_SaveEntry_Call {
	_c.Call.Return(run)
	return _c
}
